### ISSUE TITLE
windows port?

### ISSUE THREAD

**Issue by droundy** [lilydjwg/rust-signalbool#1]
I know this is a bit early, but it'd be lovely to see a cross-platform signal-handling library, and I like the simple approach you're using here.  I don't know much about windows, but I do know that you can catch the equivalent of SIGINT, which is pretty much all I care about.

**Comment by lilydjwg** [comment]
I guess I can steal code from ctrlc :-)

**Comment by lilydjwg** [comment]
I've added a windows branch. Would you give it a try?
