### ISSUE TITLE
Remove nix from API

### ISSUE THREAD

**Issue by droundy** [lilydjwg/rust-signalbool#2]
It'd be lovely to have an API that does not require nix.

**Comment by lilydjwg** [comment]
What do you mean by "API"? The crate depends on nix but doesn't require you to import it yourself. However, you may find it more easy to use nix if you need to do things like `pthread_sigmask`.

**Comment by droundy** [comment]
I refer to the use of `nix::Result` as a return type.  I haven't looked this type up, but why not return `io::Result`? Then users of this package won't have to look in nix to figure out how to deal with the output of this package.

**Comment by lilydjwg** [comment]
I see. I've fixed it.
